external_data_config:
  external_data_csv: data/external/train.csv
  external_casting_ok_data_csv: data/external/casting_data/ok_front
  external_casting_def_data_csv: data/external/casting_data/def_front

raw_data_config:
  raw_data: data/raw/casting_data
  train_test_split_ratio: 0.1
  target: churn 
  random_state: 111
  new_train_data_csv: data/raw/train_new.csv

processed_data_config:
  train_casting_data: data/processed/casting_data/train
  test_casting_data:  data/processed/casting_data/test

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: model_iteration1
  run_name: neural_network
  registered_model_name: Neural Network
  remote_server_uri: http://localhost:1234
 
random_forest: 
  max_depth: 10
  n_estimators: 30

model_dir: models/model.joblib

model_webapp_dir: webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: reports/data_and_target_drift_dashboard.html
